
<?php $title = 'Connexion';

$this->headTitle($title); ?>
<h1><?= $this->escapeHtml($title); ?></h1> 
<div class = "jumbotron">
<?php 
$form->setAttribute('action', $this->url('user', ['action' => 'connexion']));
?>
<?php 
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('password'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</div>